---
- name: application | link profile to terminal
  file: src={{ item }}
        dest=~/Library/Application Support/iTerm2/DynamicProfiles/{{ item | basename }}
        state=link
        force=yes 
  loop:
    - 'ruby.json'
