---
- name: application | link profile to terminal
  file: src={{ ansible_env.PWD }}/roles/application/files/{{ item }}
        path='~/Library/Application Support/iTerm2/DynamicProfiles/{{ item }}'
        state=link
        force=yes
  loop:
    - ruby.json
